branch: master
directory:
- ./base/envs/local
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- terraform
secrets-scan-file-type: []
skip-check:
- LOW
- CKV_AZURE_110
- CKV_AZURE_109
- CKV_AZURE_42
