name: 'base-test-dev'
on:
  push:
    pathes:
      - ./base/**
  pull_request:
    branches:
      - main
jobs:
  terraform:
    uses: ./.github/workflows/base-var-dev.yaml
    with:
      called_from: 'test'
    secrets: inherit


