name: 'dev-test-structure'

on:
  push:
    path:
      - ./structure/**
      - ./.github/workflows/*-structure.yaml
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    uses: ./.github/workflows/template-test-structure.yaml
    with:
      backend_resource_group_name: 'TerraformRG'
      backend_storage_account_name: 'rice1goutfstate'
      backend_container_name: 'devtfstate'
      backend_key: 'dev-structure.tfstate'
      skip_check: LOW
      environment: 'develop'
      working_directory: './structure/envs/develop/'
      base_resource_group_name: 'DevBaseRG'
      structure_resource_group_name: 'DevStructureRG'
      location: 'japaneast'
    secrets: inherit