name: 'dev-test-network'

on:
  push:
    branches:
      - feature/*
    path:
      - ./network/**
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    uses: ./.github/workflows/template-test-network.yaml
    with:
      backend_resource_group_name: 'TerraformRG'
      backend_storage_account_name: 'rice1goutfstate'
      backend_container_name: 'devtfstate'
      backend_key: 'dev-network.tfstate'
      environment: 'develop'
      working_directory: './network/envs/develop/'
      network_resource_group_name: 'DevNetworkRG'
      location: 'japaneast'
      address_space: '["10.1.0.0/16"]'
