name: 'dev-test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    uses: ./.github/workflows/template-test.yaml
    with:
      backend_resource_group_name: "DevNetworkRG"
      backend_storage_account_name: "rice1gou"
      backend_container_name: "devtfstate"
      backend_key: "dev-network.tfstate"
      environment: "develop"
